### ISSUE TITLE
tooltips

### ISSUE THREAD

**Issue by ryestew** [Machinalabs/remix-etherscan-plugin#2]
the plugin has 3 navigational icons:

Ideally the active screen would have its icon in white in a dark theme or black in a light theme.  Check how the icon panel in Remix works - I believe there is a css filter.

But more importantly, the icons need tool tips - Home, Receipts, &API Key.

This last one is a minor point but I think the icons need a few more pixels of margin between them. Currently its 0.2REM but  I think 0.4rem is better.

If you can pick up these now that would be great - if you think there will be a delay then maybe we should go ahead and merge - because these points can all be done later.

**Comment by defiboy** [comment]
I have fixed the issues but there is pending thing that I cannot solve, mostly it depends of answering this question.

Is there a way a plugin could know if the themeType is dark or light?

**Comment by defiboy** [comment]
ok, all issues are already solved !
